baseURL: "https://adityatelange.github.io/hugo-PaperMod/"
title: PaperMod
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: WiKi
                  url: https://github.com/adityatelange/hugo-PaperMod/wiki/
                - name: Discord
                  url: https://discord.gg/ahpmTvhVmp
        profileMode:
            enabled: true
            title: PaperMod
            imageUrl: "./assets/headshot.png"
            imageTitle: ProfileMode image
            # imageWidth: 120
            # imageHeight: 120
            subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
            buttons:
                - name: Blog
                  url: posts
                - name: Profile Mode
                  url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode