baseURL = "/"
title = "Shawn's Portfolio"
description = "Where I store information"

enableRobotsTXT = true

###############################################################################
# Docsy
###############################################################################

enableGitInfo = true
enableEmoji = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Comment out to enable taxonomies in Docsy
disableKinds = ["taxonomy"]

###############################################################################
# Hugo - Top-level navigation (horizontal)
###############################################################################
[menu]
  [[menu.main]]
    name = "About"
    weight = -1000
    pre = "<i class='fa-solid fa-user pr-2' style='color: #FFC107'></i>"
    url = "/#about-section"
  [[menu.main]]
    name = "Documentation"
    weight = -101
    pre = "<i class='fas fa-book pr-2' style='color: #FFC107'></i>"
    url = "/docs/"
  [[menu.main]]
    name = "Projects"
    weight = -100
    pre = "<i class='fa-solid fa-screwdriver-wrench pr-2' style='color: #FFC107'></i>"
    url = "/projects/"
  [[menu.main]]
    name = "Blog"
    weight = -90
    pre = "<i class='fa-solid fa-seedling pr-2' style='color: #FFC107'></i>"
    url = "/blog/"
  [[menu.main]]
    name = "GitHub"
    weight = -10
    pre = "<i class='fab fa-github pr-2' style='color: #FFC107'></i>"
    post = "<br><span class='badge badge-warning'>Add me here!</span>"
    url = "https://github.com/shawnzhang12/"

# Configure how URLs look like per section.
# [permalinks]
# blog = "/:section/:year/:month/:day/:slug/"

###############################################################################
# Docsy - Goldmark markdown parser
###############################################################################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    guessSyntax = "true"

###############################################################################
# Docsy - Mermaid configuration
###############################################################################
[params.mermaid]
enable = true

###############################################################################
# Docsy - Image processing configuration
###############################################################################
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

[params.drawio]
enable = true
###############################################################################
# Docsy - Services configuration
###############################################################################
# [services]
#   [services.googleAnalytics]
#   id = "what"

# Language configuration

[languages]
  [languages.en]
    title = "Shawn's Portfolio"
    languageName = "English"
    # Weight used for sorting.
    weight = 1
    [languages.en.params]
      description = "My digital memory bank"


# Comment out if you don't want the "print entire section" link enabled.
#[outputs]
#section = ["HTML", "print", "RSS"]

[params]
copyright = "Shawn Zhang"
privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
#url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/shawnzhang12"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/google/shawnzhang/portfolio"


# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "d72aa9b2712488cc3"


# User interface configuration
[params.ui]
# Show expand/collapse icon for sidebar sections
sidebar_menu_foldable = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = true
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

[params.logo]
image = "/logo.svg"

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'


[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
  name = "GitHub"
  url = "https://github.com/shawnzhang12/"
  icon = "fab fa-github"
  desc = "Where development takes place"
[[params.links.user]]
  name ="Linkedin"
  url = "https://www.linkedin.com/in/shawnzhang12/"
  icon = "fab fa-linkedin"
  desc = "Connect with me here!"
[[params.links.user]]
  name = "Goodreads"
  url = "https://www.goodreads.com/shawnzhang12/"
  icon = "fab fa-goodreads"
  desc = "Reading time"


[module]
  # Uncomment the next line to build and serve using local docsy clone declared in the named Hugo workspace:
  # workspace = "docsy.work" 
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
